### ISSUE TITLE
Update item creation flow to allow "and/or" class restrictions

### ISSUE THREAD

**Issue by ECWireless** [raid-guild/character-sheets-frontend#138]
- For instance, you should be able to claim a certain sword if you are a Warrior or a Paladin

**Comment by dan13ram** [comment]
- Divide item creation into 3 steps.
- Better UX for requirements

References:

![Screenshot from 2024-03-07 20-06-10](https://github.com/raid-guild/character-sheets-frontend/assets/10012209/5ab23940-65dc-40b6-9d70-bbff468a1017)
![Screenshot from 2024-03-07 20-06-19](https://github.com/raid-guild/character-sheets-frontend/assets/10012209/6dc620f4-ca40-4101-ba6f-5fd646805d3d)
![Screenshot from 2024-03-07 20-06-40](https://github.com/raid-guild/character-sheets-frontend/assets/10012209/15d8dbf6-4d15-476f-a44b-091705529624)
![Screenshot from 2024-03-07 20-07-58](https://github.com/raid-guild/character-sheets-frontend/assets/10012209/b3545bc9-3fa3-462f-8fda-5424d49c2221)
