### ISSUE TITLE
Dynamically render recent characters and items to landing page

### ISSUE THREAD

**Issue by ECWireless** [raid-guild/character-sheets-frontend#81]
- Right now, we are rendering a dummy character
- There is a design for rendering the most recent character, but we most likely need to update the design to include recent items
- We also may want to consider rendering "featured" things

**Comment by dan13ram** [comment]
@ECWireless By most recent are you thinking "last created", "last updated", or something else? 
Neither of those might be the one we want to feature? 
Perhaps the character with the most experience?

**Comment by ECWireless** [comment]
> @ECWireless By most recent are you thinking "last created", "last updated", or something else? Neither of those might be the one we want to feature? Perhaps the character with the most experience?

I was initially thinking that it should be the "last created," but I guess that means there will be a boring character on the front.  If we make it the character with the most XP, though, then potentially any game creator could create a game and mint their character a huge amount of XP to get on the front. Maybe on the production deployment we restrict it to highest XP in the RaidGuild game?

**Comment by dan13ram** [comment]
That makes sense. In the dev game it doesn't really matter so we can just leave it as the highest XP in any game.
